// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypthxxthcyzfvmxlhbdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwdGh4eHRoY3l6ZnZteGxoYmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDkwMjEsImV4cCI6MjA2ODc4NTAyMX0.hkcDmwy7e6T9ZtpqaTPZuT1Qnnz0FmB7uUoJdqqOROE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});